# Generated by Django 6.0.4 on 2026-04-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_resume_name_resume_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('PROCESSING', 'Processing')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Untitled Resume', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
