# Generated by Django 6.0.4 on 2026-05-14 15:09

import generator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_resume_options_resume_data_resume_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='data',
            field=models.JSONField(blank=True, default=dict, validators=[generator.validators.validate_resume_data]),
        ),
    ]
