# Generated by Django 6.0.4 on 2026-07-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_resume_is_favorite_resume_score_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
